substitutions:
  name: ict-plug
  friendly_name: "ICT Plug"

  # substitutions for power monitoring calibration.  Allows end users to change calibration in their yaml and still
  # incorporate this file as a package to get all the updates we release.
  voltage_divider_val:  "2001"
  sub_hlw_model:         BL0937
  current_resistor_val: "0.001"
  power_cal_val1_in:    "0.0"
  power_cal_val1_out:   "0.0"
  power_cal_val2_in:    "879.4"
  power_cal_val2_out:   "750"
  current_cal_val1_in:  "0.0"
  current_cal_val1_out: "0.0"
  current_cal_val2_in:  "6.8"
  current_cal_val2_out: "3.5"
  voltage_cal_val1_in:  "0.0"
  voltage_cal_val1_out: "0.0"
  voltage_cal_val2_in:  "132.7"
  voltage_cal_val2_out: "119.1"

  # set power monitoring mode in yaml, selecting the "yaml_configured" option in the select entity will cause these
  # values to be used after next reboot.
  sub_change_mode_every: "1"
  sub_update_interval: 10s
  sub_initial_mode: CURRENT

  # GPIO definitions
  sub_red_led_pin:  GPIO1
  sub_button_pin:   GPIO3
  sub_pm_cf_pin:    GPIO4
  sub_pm_cf1_pin:   GPIO5
  sub_blue_led_pin: GPIO12
  sub_relay_pin:    GPIO13
  sub_pm_sel_pin:   GPIO14

esphome:
  name: $name
  friendly_name: $friendly_name
  project:
    name: "ICT.PLF12"
    version: "1.1.0"

esp8266:
  board: esp01_1m
  restore_from_flash: true
  early_pin_init: false

wifi:
  ssid: $name
  password: $name
  fast_connect: True
  ap:

web_server:
  include_internal: true

captive_portal:
logger:
api:
ota:

# red led, blink when not connected to wifi or Home Assistant
status_led:
    pin:
      number: $sub_red_led_pin
      inverted: true

binary_sensor:
    # button input toggles relay and thereby blue led
  - platform: gpio
    id: button
    name: None
    pin:
      number: $sub_button_pin
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_on: 50ms
    on_press:
      then:
        switch.toggle: relay

switch:
    # blue LED follows relay power state
  - platform: gpio
    id: blue_led
    pin:
      number: $sub_blue_led_pin
      inverted: true
    restore_mode: RESTORE_DEFAULT_ON

    # relay output
  - platform: gpio
    id: relay
    name: None
    pin: $sub_relay_pin
    restore_mode: RESTORE_DEFAULT_ON
    # automatically make blue led equal relay state
    on_turn_on:
      - switch.turn_on: blue_led
    on_turn_off:
      - switch.turn_off: blue_led

# clock input from Home Assistant used to calculate total daily energy
time:
  - platform: homeassistant
    id: homeassistant_time

sensor:   # Power monitoring sensors output to Home Assistant
  - platform: hlw8012
    id: hlw_main
    sel_pin:
      number: $sub_pm_sel_pin
      inverted: True
    cf_pin: $sub_pm_cf_pin
    cf1_pin: $sub_pm_cf1_pin
    current_resistor: $current_resistor_val
    voltage_divider: $voltage_divider_val
    change_mode_every: $sub_change_mode_every
    update_interval: $sub_update_interval
    initial_mode: $sub_initial_mode
    model: $sub_hlw_model
    power:
      name: Power
      unit_of_measurement: W
      id: wattage
      filters:
        - calibrate_linear:
            - $power_cal_val1_in -> $power_cal_val1_out
            - $power_cal_val2_in -> $power_cal_val2_out
    current:
      name: Current
      unit_of_measurement: A
      id: current
      filters:
        - calibrate_linear:
            - $current_cal_val1_in -> $current_cal_val1_out
            - $current_cal_val2_in -> $current_cal_val2_out
    voltage:
      name: Voltage
      unit_of_measurement: V
      id: voltage
      filters:
        - calibrate_linear:
            - $voltage_cal_val1_in -> $voltage_cal_val1_out
            - $voltage_cal_val2_in -> $voltage_cal_val2_out

    # Reports the total Power so-far each day, resets at midnight
  - platform: total_daily_energy
    name: Total Daily Energy
    power_id: wattage
    filters:
        - multiply: 0.001  ## convert Wh to kWh
    unit_of_measurement: kWh
